//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cerime
    {
        public int ID { get; set; }
        public decimal Mebleg { get; set; }
        public bool Odenilibmi { get; set; }
        public System.DateTime OdenmeTarixi { get; set; }
        public string Sebeb { get; set; }
        public int IstifadechiID { get; set; }
        public int IcareID { get; set; }
        public System.DateTime CerimeTarixi { get; set; }
    
        public virtual Icare Icare { get; set; }
        public virtual Istifadechi Istifadechi { get; set; }
    }
}
