//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Icare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Icare()
        {
            this.Cerimeler = new HashSet<Cerime>();
        }
    
        public int ID { get; set; }
        public decimal IcareQiymeti { get; set; }
        public System.DateTime IcareTarixi { get; set; }
        public System.DateTime SonTarix { get; set; }
        public System.DateTime QaytarilmaTarixi { get; set; }
        public bool Qaytarilibmi { get; set; }
        public string Statusu { get; set; }
        public int IstifadechiID { get; set; }
        public int KitabID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cerime> Cerimeler { get; set; }
        public virtual Istifadechi Istifadechi { get; set; }
        public virtual Kitab Kitab { get; set; }
    }
}
