//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Istifadechi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Istifadechi()
        {
            this.Cerimeler = new HashSet<Cerime>();
            this.Icareler = new HashSet<Icare>();
        }
    
        public int ID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public System.DateTime DoghumTarixi { get; set; }
        public string Cins { get; set; }
        public string FinKod { get; set; }
        public string Email { get; set; }
        public string TelefonNo { get; set; }
        public string Adres { get; set; }
        public string IstifadechiAdi { get; set; }
        public string Shifre { get; set; }
        public bool Aktivdirmi { get; set; }
        public System.DateTime QeydiyyatTarixi { get; set; }
        public int RolID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cerime> Cerimeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Icare> Icareler { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
