//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitab()
        {
            this.Icareler = new HashSet<Icare>();
        }
    
        public int ID { get; set; }
        public string KitabAdi { get; set; }
        public int MuellifID { get; set; }
        public int KateqoriyaID { get; set; }
        public decimal IcareQiymeti { get; set; }
        public bool StokdaVarmi { get; set; }
        public string Qeyd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Icare> Icareler { get; set; }
        public virtual Kateqoriya Kateqoriya { get; set; }
        public virtual Muellif Muellif { get; set; }
    }
}
