//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryManagementSystemEntities : DbContext
    {
        public LibraryManagementSystemEntities()
            : base("name=LibraryManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Cerime> Cerimeler { get; set; }
        public virtual DbSet<Icare> Icareler { get; set; }
        public virtual DbSet<Istifadechi> Istifadechiler { get; set; }
        public virtual DbSet<Kateqoriya> Kateqoriyalar { get; set; }
        public virtual DbSet<Kitab> Kitablar { get; set; }
        public virtual DbSet<Muellif> Muellifler { get; set; }
        public virtual DbSet<Rol> Rollar { get; set; }
    }
}
